REALM_FRAGS := cca-realm-claims.cddl
REALM_FRAGS += cca-realm-challenge.cddl
REALM_FRAGS += cca-realm-extensible-measurements.cddl
REALM_FRAGS += cca-realm-hash-algo-id.cddl
REALM_FRAGS += cca-realm-initial-measurement.cddl
REALM_FRAGS += cca-realm-measurement.cddl
#REALM_FRAGS += cca-realm-mec-policy.cddl
REALM_FRAGS += cca-realm-personalization-value.cddl
REALM_FRAGS += cca-realm-profile.cddl
REALM_FRAGS += cca-realm-public-key-hash-algo-id.cddl
REALM_FRAGS += cca-realm-public-key.cddl
REALM_FRAGS += cca-realm-mec-policy.cddl
REALM_FRAGS += cca-realm-lfa-policy.cddl
REALM_FRAGS += cca-realm-instance-id.cddl
REALM_FRAGS += cca-realm-devices-token-hash.cddl
REALM_FRAGS += COSE_Key.cddl
REALM_FRAGS += ../platform/arm-platform-hash-types.cddl
REALM_FRAGS += ../platform/eat-ueid-rand.cddl

REALM_EXAMPLES := $(wildcard examples/*.diag)
