arm-platform-profile-label = 265 ; EAT profile

arm-platform-profile-type = "tag:arm.com,2026:cca_platform#2.0.0" /
                            "tag:arm.com,2026:cca_platform#2.0.0;delegated" /
                            "tag:arm.com,2026:cca_platform#2.0.0;HESRAK" /
                            "tag:arm.com,2026:cca_platform#2.0.0;direct"

arm-platform-profile = (
    arm-platform-profile-label => arm-platform-profile-type
)
