cca-devices-label = 44259

cca-device = {
    1 => arm-platform-hash-type,     ; device identity digest
    2 => arm-platform-hash-type,     ; device measurements exchange digest
    ? 3 => arm-platform-hash-type,   ; protocol negotiation data digest
    4 => bool,              ; coherent traffic IDE protection
    5 => bool,              ; non-coherent traffic IDE protection
}

cca-devices = (
    cca-devices-label => [ + cca-device ]
)
